project_id = "vopuzvbykyyxayiaiiwz"

[functions.tech-interview]
verify_jwt = true

[functions.analyze-resume]
verify_jwt = true

[functions.generate-exam]
verify_jwt = true

[functions.evaluate-exam]
verify_jwt = true

[functions.financial-advisor]
verify_jwt = true

[functions.execute-code]
verify_jwt = false

[functions.ai-code-assistant]
verify_jwt = false
